### ISSUE TITLE
Save getting corrupted after 01/01/1937

### ISSUE THREAD

**Issue by thecaptain0101** [scuffed56/SCUFFED5.0#108]
![image](https://github.com/scuffed56/SCUFFED5.0/assets/99228318/c3a023bd-4819-4ed0-98ff-1e7b35d06a5f)
All of my armies get deleted and land units are unassignable to new units. Seems to take effect after Jan. 1 1937 as a save from 1936 works perfectly fine but a save from 1937 has this issue. Has happened twice already in two singleplayer games and one multiplayer.

The Mods I'm using:

![image](https://github.com/scuffed56/SCUFFED5.0/assets/99228318/d07c5aeb-6b26-498b-9271-73f79b591de2)

The only mod that is non ironman besides scuffed is demand it, everything else is ironman and I've tried to make sure that none of them conflict with any of the mods presented in scuffed.

**Comment by thecaptain0101** [comment]
For what it's worth, r56 had this same issue back when BBA first came out and it was first updated, but I believe a later patch fixed this issue in normal r56

**Comment by atomicplan666** [comment]
We hosted a game last night that went way past 1937, i'm assuming that one of your other mods is causing this issue.

**Comment by thecaptain0101** [comment]
> 

The issue isn't getting past 1937, its loading a save after 1937 if you've shut down your game and had to relaunch. R56 had an issue like that a few months ago but I think they released a hot fix for it because it was related to the planes in BBA. The mods I'm using besides demand it and scuffed are Ironman mods and are merely cosmetic in nature, and if there were a conflict it would have presented itself much earlier.

**Comment by jgDarkWolf** [comment]
Ship designer is an iron man mod? I'd assume it would be due to overlapping code that and demand it probably interferes with some other kind of state transfer tool / host tool codes.
