### ISSUE TITLE
Turkey - Kurdistan

### ISSUE THREAD

**Issue by atomicplan666** [scuffed56/SCUFFED5.0#12]
After Turkey has defeated a Kurdish rebellion they continue to rise up forever.

Kurds should only rise up once. Maybe twice is it's saucy.

**Comment by xfrenzzyy** [comment]
Not sure on how that works, I do know that when I seen it happen it my game the Turkey had low ass stability for the majority of the game not sure if that affects it.

**Comment by Juddur** [comment]
Can't find anything specifically about kurdistan rising up, just seems to be a regular thing, however a focus could be added to put a state modifer down to exodus the local population, then making said modifer another ver. of "kurdish rebellion" state modfiers mechanics
