### ISSUE TITLE
AI Force attack / Last Stand

### ISSUE THREAD

**Issue by atomicplan666** [scuffed56/SCUFFED5.0#17]
Remove this?

**Comment by Fullchord** [comment]
The only reason this is an issue for anyone is with large minors such as ai China or ai Poland, both of which don't really need to be nerfed at all.

**Comment by atomicplan666** [comment]
Force attacking AI is a problem because it seems like the AI doesn't actually use command power. All AI force attacks, not just poland and China (me remembering watching Hanker Boy die to romania). Force attack is bullshit ESPECIALLY when it's an AI pressing the funny button. AI should not have funny button.

**Comment by atomicplan666** [comment]
We'll keep it
